update

diff --git a/.github/workflows/sr_cfg.yml b/.github/workflows/sr_cfg.yml
--- a/.github/workflows/sr_cfg.yml
+++ b/.github/workflows/sr_cfg.yml
@@ -31,12 +31,12 @@ jobs:
 
       # BLOCK RULES
       # ADGUARD_DNS_REJECT_URL:         https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt
-      # RAW_RULESET_BLOCKHTTPDNS_URL:   https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/BlockHttpDNS/BlockHttpDNS.list
       # DANPOLLOCK_REJECT_URL:          https://someonewhocares.org/hosts/hosts
       # RAW_LIST_BLOCK_LIST_URL:        https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/reject-list.txt
       # PETERLOWE_REJECT_URL:           https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=1&mimetype=plaintext
       # RAW_RULESET_ADVERTISING_URL:        https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Advertising/Advertising.list
       RAW_RULESET_ADVERTISINGLITE_URL:    https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/AdvertisingLite/AdvertisingLite.list
+      RAW_RULESET_BLOCKHTTPDNS_URL:       https://raw.githubusercontent.com/blackmatrix7/izos_rule_script/master/rule/Clash/BlockHttpDNS/BlockHttpDNS.list
 
       # PROXY RULES
       RAW_RULESET_PROXY_URL:              https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ProxyLite/ProxyLite.list
@@ -83,27 +83,18 @@ jobs:
           echo "RELEASE_NAME=Updated on $(date +%Y%m%d%H%M)" >> $GITHUB_ENV
           echo "TAG_NAME=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
 
-      - name: Download Files 1
+      - name: Download Files
         run: |
           # Create temp folder
           rm -rf $GITHUB_WORKSPACE/tmp && mkdir -p $GITHUB_WORKSPACE/tmp
-
-      - name: Download Files 2 1
-        run: |
           # Download Direct Rules
           curl ${{ env.RAW_RULESET_DIRECT_URL }} > $GITHUB_WORKSPACE/tmp/warp_ruleset.txt || (echo "Download ${{ env.RAW_RULESET_DIRECT_URL }} Failed!" && exit 1)
-      - name: Download Files 2 2
-        run: |
           # Download Proxy Rules
           curl ${{ env.RAW_RULESET_PROXY_URL }} > $GITHUB_WORKSPACE/tmp/proxy_ruleset.txt || (echo "Download ${{ env.RAW_RULESET_PROXY_URL }} Failed!" && exit 1)
-      - name: Download Files 2 3
-        run: |
           # Download Block Rules
           curl ${{ env.RAW_RULESET_ADVERTISINGLITE_URL }} > $GITHUB_WORKSPACE/tmp/block_ruleset.txt || (echo "Download ${{ env.RAW_RULESET_ADVERTISINGLITE_URL }} Failed!" && exit 1)
-          # curl ${{ env.RAW_RULESET_BLOCKHTTPDNS_URL }} >> $GITHUB_WORKSPACE/tmp/block_ruleset.txt || (echo "Download ${{ env.RAW_RULESET_BLOCKHTTPDNS_URL }} Failed!" && exit 1)
+          curl ${{ env.RAW_RULESET_BLOCKHTTPDNS_URL }} >> $GITHUB_WORKSPACE/tmp/block_ruleset.txt || (echo "Download ${{ env.RAW_RULESET_BLOCKHTTPDNS_URL }} Failed!" && exit 1)
           # wget ${{ env.ADGUARD_DNS_REJECT_URL }} -O $GITHUB_WORKSPACE/tmp/adguard_dns_list.txt || (echo "Download ${{ env.ADGUARD_DNS_REJECT_URL }} Failed!" && exit 1)
-      - name: Download Files 3
-        run: |
           # Download Warp Rules
           curl ${{ env.RAW_RULESET_ORACLE_URL }} > $GITHUB_WORKSPACE/tmp/warp_ruleset.txt || (echo "Download ${{ env.RAW_RULESET_ORACLE_URL }} Failed!" && exit 1)
           curl ${{ env.RAW_RULESET_OPENAI_URL }} >> $GITHUB_WORKSPACE/tmp/warp_ruleset.txt || (echo "Download ${{ env.RAW_RULESET_OPENAI_URL }} Failed!" && exit 1)
@@ -117,8 +108,6 @@ jobs:
           curl ${{ env.RAW_RULESET_FACEBOOK_URL }} >> $GITHUB_WORKSPACE/tmp/warp_ruleset.txt || (echo "Download ${{ env.RAW_RULESET_FACEBOOK_URL }} Failed!" && exit 1)
           curl ${{ env.RAW_RULESET_MICROSOFT_URL }} >> $GITHUB_WORKSPACE/tmp/warp_ruleset.txt || (echo "Download ${{ env.RAW_RULESET_MICROSOFT_URL }} Failed!" && exit 1)
           curl ${{ env.RAW_RULESET_CLOUDFLARE_URL }} >> $GITHUB_WORKSPACE/tmp/warp_ruleset.txt || (echo "Download ${{ env.RAW_RULESET_CLOUDFLARE_URL }} Failed!" && exit 1)
-      - name: Download Files 4
-        run: |
           # Download Apple Rules
           curl ${{ env.RAW_RULESET_APPLE_URL }} > $GITHUB_WORKSPACE/tmp/apple_ruleset.txt || (echo "Download ${{ env.RAW_RULESET_APPLE_URL }} Failed!" && exit 1)
           curl ${{ env.RAW_RULESET_APPLEDAILY_URL }} >> $GITHUB_WORKSPACE/tmp/apple_ruleset.txt || (echo "Download ${{ env.RAW_RULESET_APPLEDAILY_URL }} Failed!" && exit 1)
@@ -134,6 +123,7 @@ jobs:
           curl ${{ env.RAW_RULESET_ICLOUD_URL }} >> $GITHUB_WORKSPACE/tmp/apple_ruleset.txt || (echo "Download ${{ env.RAW_RULESET_ICLOUD_URL }} Failed!" && exit 1)
           curl ${{ env.RAW_RULESET_ICLOUDPRIVATERELAY_URL }} >> $GITHUB_WORKSPACE/tmp/apple_ruleset.txt || (echo "Download ${{ env.RAW_RULESET_ICLOUDPRIVATERELAY_URL }} Failed!" && exit 1)
           curl ${{ env.RAW_RULESET_SIRI_URL }} >> $GITHUB_WORKSPACE/tmp/apple_ruleset.txt || (echo "Download ${{ env.RAW_RULESET_SIRI_URL }} Failed!" && exit 1)
+
 
       - name: Process Apple Rules
         run: |
